services:
  backend:
    build: ./backend
    container_name: yuanhao_backend
    image: yuanhao_flask_backend
    volumes:
      - ./logs:/logs
    expose:
      - "5000"
    environment:
      - LOG_PATH=/logs

  frontend:
    image: nginx:latest
    container_name: yuanhao_frontend
    ports:
      - "8083:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

